//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }

        [Display(Name = "Departman Adý")]
        [Required(ErrorMessage ="Lütfen Bir Departman Seçiniz!")]
        public Nullable<int> DepartmanId { get; set; }

        [Required(ErrorMessage ="Ad Alaný Zorunludur!")]
        public string Ad { get; set; }

        [Required(ErrorMessage = "Soyad Alaný Zorunludur!")]
        public string Soyad { get; set; }

        [Display(Name = "Maaþ")]
        [Required(ErrorMessage ="Maaþ Alaný Zorunludur!")]
        [Range(1600, 8000, ErrorMessage ="Maaþ Alaný 1600 ile 8000 arasýnda olmalýdýr!")]
        public Nullable<short> Maas { get; set; }

        [Display(Name = "Doðum Tarihi")]
        [Required(ErrorMessage = "Lütfen Doðum Tarihi Giriniz!")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }

        [Required(ErrorMessage = "Lütfen Cinsiyeti Belirtiniz!")]
        public bool Cinsiyet { get; set; }

        [Display(Name = "Evlilik Durumu")]
        public bool EvliMi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
